#!/usr/bin/env python3
"""Personal TestFlight helper for the aboimila/noop fork (see NOOP_TESTFLIGHT.md).

Used only by .github/workflows/noop-testflight.yml. Three subcommands:

  check-settings  Ask xcodebuild for each iOS-family target's resolved build settings and fail
                  unless bundle ids, the App Group, entitlement files and SKIP_INSTALL are what
                  the Apple registrations expect.
  embed           Ad-hoc sign every bundle in an UNSIGNED archive, inside out, with its own
                  resolved entitlements. The archive is built with CODE_SIGNING_ALLOWED=NO so
                  Xcode never asks Apple for a development profile (which needs a registered
                  device); an unsigned Mach-O carries no entitlements, and the App Store export
                  re-signs with whatever the archived binary declares. Without this step the
                  exported app would lose HealthKit and the App Group.
  verify          Inspect a finished app (archive or exported .ipa) and fail if any required
                  identifier, version, entitlement, Info.plist permission or (in distribution
                  mode) App Store signing property is missing.

Pure checks live in plain functions so they can be unit tested on any OS
(test_noop_testflight.py); everything that shells out to codesign/security/xcodebuild is macOS-only.
"""

from __future__ import annotations

import argparse
import json
import os
import plistlib
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

HEALTHKIT = "com.apple.developer.healthkit"
HEALTHKIT_BACKGROUND = "com.apple.developer.healthkit.background-delivery"
APP_GROUPS = "com.apple.security.application-groups"


@dataclass(frozen=True)
class BundleSpec:
    """One signed bundle inside NOOP.app."""

    name: str
    rel_path: str  # relative to NOOP.app ("" = the app itself)
    id_suffix: str  # appended to BUNDLE_ID_PREFIX
    entitlements_src: str  # repo-relative, regenerated by xcodegen from project.yml
    target: str  # Xcode target name
    is_app: bool
    # Entitlements that must be present and true in the signed bundle (the App Group is always
    # required). com.apple.developer.healthkit.access is reported but not required: it only gates
    # clinical/verifiable health records, which NOOP does not use.
    required_true: tuple[str, ...] = ()
    info_nonempty: tuple[str, ...] = ()
    extra: dict = field(default_factory=dict)

    def bundle_id(self, prefix: str) -> str:
        return prefix + self.id_suffix


# Inside-out order: a bundle is always signed before the bundle that contains it.
BUNDLES: tuple[BundleSpec, ...] = (
    BundleSpec(
        name="NOOPWatchComplications",
        rel_path="Watch/NOOPWatch.app/PlugIns/NOOPWatchComplications.appex",
        id_suffix=".noop.watch.complications",
        entitlements_src="NOOPWatchComplications/NOOPWatchComplications.entitlements",
        target="NOOPWatchComplications",
        is_app=False,
    ),
    BundleSpec(
        name="NOOPWatch",
        rel_path="Watch/NOOPWatch.app",
        id_suffix=".noop.watch",
        entitlements_src="NOOPWatch/NOOPWatch.entitlements",
        target="NOOPWatch",
        is_app=True,
        required_true=(HEALTHKIT,),
        info_nonempty=("NSHealthShareUsageDescription", "NSHealthUpdateUsageDescription"),
        extra={"companion": True},
    ),
    BundleSpec(
        name="NOOPWidgets",
        rel_path="PlugIns/NOOPWidgets.appex",
        id_suffix=".noop.widgets",
        entitlements_src="StrandiOSWidgets/NOOPWidgets.entitlements",
        target="NOOPiOSWidgets",
        is_app=False,
    ),
    BundleSpec(
        name="NOOP",
        rel_path="",
        id_suffix=".noop",
        entitlements_src="StrandiOS/Resources/NOOP.entitlements",
        target="NOOPiOS",
        is_app=True,
        required_true=(HEALTHKIT, HEALTHKIT_BACKGROUND),
        info_nonempty=(
            "NSBluetoothAlwaysUsageDescription",
            "NSHealthShareUsageDescription",
            "NSHealthUpdateUsageDescription",
        ),
        extra={"background_modes": ("bluetooth-central",)},
    ),
)

MAIN = BUNDLES[-1]


class CheckFailed(Exception):
    pass


def app_group_for(prefix: str) -> str:
    # Mirrors project.yml: APP_GROUP_ID = group.$(BUNDLE_ID_PREFIX).noop.staging
    return f"group.{prefix}.noop.staging"


def log(msg: str) -> None:
    print(msg, flush=True)


def gh_error(msg: str) -> None:
    print(f"::error::{msg}", flush=True)


def redact(text: str, team: str | None) -> str:
    return text.replace(team, "<TEAM_ID>") if team else text


# --------------------------------------------------------------------------------------------
# Pure checks (unit tested)
# --------------------------------------------------------------------------------------------


def render_entitlements(template_text: str, app_group: str) -> dict:
    """Resolve $(APP_GROUP_ID) in a repo entitlements file. Any other unresolved $(…) is an error,
    because codesign would embed it literally and the export would reject (or silently drop) it."""
    text = template_text.replace("$(APP_GROUP_ID)", app_group)
    if "$(" in text:
        raise CheckFailed("entitlements template has an unresolved build setting other than APP_GROUP_ID")
    return plistlib.loads(text.encode())


def check_entitlements(spec: BundleSpec, ents: dict, app_group: str, *, mode: str,
                       team: str | None, prefix: str) -> list[str]:
    problems: list[str] = []
    for key in spec.required_true:
        if ents.get(key) is not True:
            problems.append(f"{spec.name}: entitlement {key} is {ents.get(key)!r}, expected true")
    groups = ents.get(APP_GROUPS)
    if not isinstance(groups, list) or app_group not in groups:
        problems.append(f"{spec.name}: App Group {app_group} missing from {APP_GROUPS} (got {groups!r})")
    if mode == "distribution":
        expected_app_id = f"{team}.{spec.bundle_id(prefix)}"
        if ents.get("application-identifier") != expected_app_id:
            problems.append(f"{spec.name}: application-identifier is {ents.get('application-identifier')!r}, "
                            f"expected {expected_app_id!r}")
        if ents.get("com.apple.developer.team-identifier") != team:
            problems.append(f"{spec.name}: team-identifier does not match APPLE_TEAM_ID")
        if ents.get("get-task-allow") is True:
            problems.append(f"{spec.name}: get-task-allow is true, i.e. a DEVELOPMENT signature")
        if spec is MAIN and ents.get("beta-reports-active") is not True:
            problems.append(f"{spec.name}: beta-reports-active is not true, so this is not an "
                            "App Store / TestFlight distribution signature")
    return problems


def check_info(spec: BundleSpec, info: dict, prefix: str, app_group: str) -> list[str]:
    problems: list[str] = []
    want_id = spec.bundle_id(prefix)
    if info.get("CFBundleIdentifier") != want_id:
        problems.append(f"{spec.name}: CFBundleIdentifier is {info.get('CFBundleIdentifier')!r}, expected {want_id!r}")
    if info.get("AppGroupIdentifier") != app_group:
        problems.append(f"{spec.name}: AppGroupIdentifier is {info.get('AppGroupIdentifier')!r}, expected {app_group!r}")
    for key in spec.info_nonempty:
        value = info.get(key)
        if not isinstance(value, str) or not value.strip():
            problems.append(f"{spec.name}: Info.plist {key} is missing or empty")
    if spec.extra.get("companion"):
        want_companion = MAIN.bundle_id(prefix)
        if info.get("WKCompanionAppBundleIdentifier") != want_companion:
            problems.append(f"{spec.name}: WKCompanionAppBundleIdentifier is "
                            f"{info.get('WKCompanionAppBundleIdentifier')!r}, expected {want_companion!r}")
    for mode in spec.extra.get("background_modes", ()):
        if mode not in (info.get("UIBackgroundModes") or []):
            problems.append(f"{spec.name}: UIBackgroundModes lacks {mode}")
    return problems


def check_versions(infos: dict[str, dict], build_number: str | None) -> list[str]:
    problems: list[str] = []
    builds = {name: info.get("CFBundleVersion") for name, info in infos.items()}
    shorts = {name: info.get("CFBundleShortVersionString") for name, info in infos.items()}
    if len(set(builds.values())) != 1:
        problems.append(f"CFBundleVersion differs between bundles: {builds}")
    if len(set(shorts.values())) != 1:
        problems.append(f"CFBundleShortVersionString differs between bundles: {shorts}")
    if build_number and builds.get(MAIN.name) != build_number:
        problems.append(f"CFBundleVersion is {builds.get(MAIN.name)!r}, expected build {build_number!r}")
    return problems


def check_profile(spec: BundleSpec, profile: dict, *, team: str, prefix: str, app_group: str) -> list[str]:
    """An App Store distribution profile: no device list, not all-devices (enterprise), no
    get-task-allow, our team, our explicit App ID, and it must grant every capability we need."""
    problems: list[str] = []
    if profile.get("ProvisionedDevices"):
        problems.append(f"{spec.name}: profile lists devices, so it is a development/ad-hoc profile")
    if profile.get("ProvisionsAllDevices"):
        problems.append(f"{spec.name}: profile provisions all devices (enterprise), not App Store")
    if team not in (profile.get("TeamIdentifier") or []):
        problems.append(f"{spec.name}: profile does not belong to APPLE_TEAM_ID")
    pents = profile.get("Entitlements") or {}
    if pents.get("get-task-allow") is True:
        problems.append(f"{spec.name}: profile allows get-task-allow (development profile)")
    want_app_id = f"{team}.{spec.bundle_id(prefix)}"
    if pents.get("application-identifier") != want_app_id:
        problems.append(f"{spec.name}: profile App ID is {pents.get('application-identifier')!r}, expected {want_app_id!r}")
    for key in spec.required_true:
        if key not in pents:
            problems.append(f"{spec.name}: provisioning profile does not grant {key}; enable the capability "
                            "on the App ID in the Apple Developer portal")
    if app_group not in (pents.get(APP_GROUPS) or []):
        problems.append(f"{spec.name}: provisioning profile does not grant App Group {app_group}; assign it to "
                        "the App ID in the Apple Developer portal")
    return problems


def check_authority(spec: BundleSpec, codesign_dvv: str) -> list[str]:
    authorities = [line.split("=", 1)[1] for line in codesign_dvv.splitlines() if line.startswith("Authority=")]
    if not authorities:
        return [f"{spec.name}: no signing authority (ad-hoc or unsigned), expected Apple Distribution"]
    leaf = authorities[0]
    if not (leaf.startswith("Apple Distribution") or leaf.startswith("iPhone Distribution")):
        return [f"{spec.name}: signed by {leaf.split(':')[0]!r}, expected 'Apple Distribution'"]
    return []


def unexpected_bundles(found: list[str]) -> list[str]:
    known = {b.rel_path for b in BUNDLES if b.rel_path}
    return sorted(p for p in found if p not in known)


# --------------------------------------------------------------------------------------------
# macOS side effects
# --------------------------------------------------------------------------------------------


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, text=True, capture_output=True)


def read_plist(path: Path) -> dict:
    with path.open("rb") as fh:
        return plistlib.load(fh)


def signed_entitlements(bundle: Path) -> dict:
    out = subprocess.run(["codesign", "-d", "--entitlements", "-", "--xml", str(bundle)],
                         capture_output=True)
    data = out.stdout.strip()
    if out.returncode != 0:
        raise CheckFailed(f"codesign could not read {bundle.name}: {out.stderr.decode(errors='replace').strip()}")
    return plistlib.loads(data) if data else {}


def nested_code_bundles(app: Path) -> list[str]:
    found = []
    for pattern in ("*.app", "*.appex"):
        for p in app.rglob(pattern):
            if p.is_dir():
                found.append(str(p.relative_to(app)))
    return found


def locate_archive_app(archive: Path) -> Path:
    products = archive / "Products"
    entries = sorted(p.name for p in products.iterdir()) if products.is_dir() else []
    if entries == ["Applications"]:
        entries += sorted(f"Applications/{p.name}" for p in (products / "Applications").iterdir())
    app = products / "Applications" / "NOOP.app"
    if entries != ["Applications", "Applications/NOOP.app"]:
        raise CheckFailed(f"archive is not a single-app iOS archive (Products contains {entries}); an embedded "
                          "target was installed on its own, which makes Xcode treat it as a generic archive")
    props = read_plist(archive / "Info.plist").get("ApplicationProperties") or {}
    if props.get("ApplicationPath") != "Applications/NOOP.app":
        raise CheckFailed(f"archive Info.plist has no ApplicationProperties for NOOP.app ({props!r})")
    return app


def sign_adhoc(path: Path, entitlements: Path | None = None) -> None:
    cmd = ["codesign", "--force", "--sign", "-", "--timestamp=none"]
    if entitlements is not None:
        cmd += ["--entitlements", str(entitlements)]
    res = run(cmd + [str(path)], check=False)
    if res.returncode != 0:
        raise CheckFailed(f"ad-hoc codesign failed for {path.name}: {res.stderr.strip()}")


def cmd_embed(args: argparse.Namespace) -> None:
    repo = Path(args.repo).resolve()
    archive = Path(args.archive).resolve()
    app = locate_archive_app(archive)
    group = app_group_for(args.prefix)

    extra = unexpected_bundles(nested_code_bundles(app))
    if extra:
        raise CheckFailed(f"unknown nested bundles would be signed without entitlements: {extra}")

    with tempfile.TemporaryDirectory() as tmp:
        for spec in BUNDLES:
            bundle = app / spec.rel_path if spec.rel_path else app
            if not bundle.is_dir():
                raise CheckFailed(f"{spec.name} is missing from the archive at NOOP.app/{spec.rel_path}")
            ents = render_entitlements((repo / spec.entitlements_src).read_text(), group)
            ent_file = Path(tmp) / f"{spec.name}.entitlements"
            with ent_file.open("wb") as fh:
                plistlib.dump(ents, fh)
            frameworks = bundle / "Frameworks"
            if frameworks.is_dir():
                for item in sorted(frameworks.iterdir()):
                    if item.suffix in (".framework", ".dylib"):
                        sign_adhoc(item)
            sign_adhoc(bundle, ent_file)
            log(f"✓ {spec.name}: ad-hoc signed with {', '.join(sorted(ents))}")


def cmd_verify(args: argparse.Namespace) -> None:
    prefix, mode, team = args.prefix, args.mode, args.team or None
    if mode == "distribution" and not team:
        raise CheckFailed("distribution verification needs --team (APPLE_TEAM_ID)")
    group = app_group_for(prefix)

    with tempfile.TemporaryDirectory() as tmp:
        if args.ipa:
            # ditto, not zipfile: zipfile drops the executable bit and would break codesign --verify.
            run(["ditto", "-x", "-k", args.ipa, tmp])
            app = Path(tmp) / "Payload" / "NOOP.app"
        else:
            app = locate_archive_app(Path(args.archive).resolve())
        if not app.is_dir():
            raise CheckFailed("NOOP.app not found")

        problems: list[str] = []
        extra = unexpected_bundles(nested_code_bundles(app))
        if extra:
            problems.append(f"unexpected nested bundles: {extra}")

        infos: dict[str, dict] = {}
        report: list[str] = []
        for spec in BUNDLES:
            bundle = app / spec.rel_path if spec.rel_path else app
            if not bundle.is_dir():
                problems.append(f"{spec.name}: missing at NOOP.app/{spec.rel_path}")
                continue
            info = read_plist(bundle / "Info.plist")
            infos[spec.name] = info
            problems += check_info(spec, info, prefix, group)
            ents = signed_entitlements(bundle)
            problems += check_entitlements(spec, ents, group, mode=mode, team=team, prefix=prefix)
            report.append(f"{spec.name} ({info.get('CFBundleIdentifier')}) "
                          f"{info.get('CFBundleShortVersionString')} ({info.get('CFBundleVersion')})")
            for key in sorted(ents):
                report.append(f"  {key} = {ents[key]!r}")
            if mode == "distribution":
                dvv = run(["codesign", "-dvv", str(bundle)], check=False).stderr
                problems += check_authority(spec, dvv)
                prof_path = bundle / "embedded.mobileprovision"
                if not prof_path.is_file():
                    problems.append(f"{spec.name}: no embedded.mobileprovision")
                else:
                    decoded = run(["security", "cms", "-D", "-i", str(prof_path)], check=False)
                    if decoded.returncode != 0:
                        problems.append(f"{spec.name}: could not decode embedded.mobileprovision")
                    else:
                        profile = plistlib.loads(decoded.stdout.encode())
                        problems += check_profile(spec, profile, team=team, prefix=prefix, app_group=group)
                        report.append(f"  profile: {profile.get('Name')!r}, expires {profile.get('ExpirationDate')}")

        problems += check_versions(infos, args.build_number)
        strict = run(["codesign", "--verify", "--deep", "--strict", str(app)], check=False)
        if strict.returncode != 0:
            problems.append(f"codesign --verify --deep --strict failed: {strict.stderr.strip()}")

        log(redact("\n".join(report), team))
        if problems:
            for p in problems:
                gh_error(redact(p, team))
            raise CheckFailed(f"{len(problems)} capability/signing check(s) failed ({mode})")
        log(f"✓ all {len(BUNDLES)} bundles passed {mode} verification")


def cmd_check_settings(args: argparse.Namespace) -> None:
    prefix = args.prefix
    group = app_group_for(prefix)
    problems: list[str] = []
    for spec in BUNDLES:
        res = run(["xcodebuild", "-project", args.project, "-target", spec.target, "-configuration",
                   "Release", "-showBuildSettings", "-json"], check=False)
        if res.returncode != 0:
            raise CheckFailed(f"xcodebuild -showBuildSettings failed for {spec.target}: {res.stderr[-2000:]}")
        # Package-resolution chatter can precede the JSON on stdout; decode from the first '['.
        start = res.stdout.find("[")
        if start < 0:
            raise CheckFailed(f"xcodebuild -showBuildSettings printed no JSON for {spec.target}")
        settings = json.JSONDecoder().raw_decode(res.stdout[start:])[0][0]["buildSettings"]
        problems += check_build_settings(spec, settings, prefix, group)
        log(f"{spec.target}: {settings.get('PRODUCT_BUNDLE_IDENTIFIER')} group={settings.get('APP_GROUP_ID')} "
            f"entitlements={settings.get('CODE_SIGN_ENTITLEMENTS')} SKIP_INSTALL={settings.get('SKIP_INSTALL')}")
    if problems:
        for p in problems:
            gh_error(p)
        raise CheckFailed(f"{len(problems)} build-setting check(s) failed")
    log("✓ build settings match the Apple registrations")


def check_build_settings(spec: BundleSpec, settings: dict, prefix: str, group: str) -> list[str]:
    problems = []
    if settings.get("PRODUCT_BUNDLE_IDENTIFIER") != spec.bundle_id(prefix):
        problems.append(f"{spec.target}: PRODUCT_BUNDLE_IDENTIFIER is {settings.get('PRODUCT_BUNDLE_IDENTIFIER')!r}, "
                        f"expected {spec.bundle_id(prefix)!r}")
    if settings.get("APP_GROUP_ID") != group:
        problems.append(f"{spec.target}: APP_GROUP_ID is {settings.get('APP_GROUP_ID')!r}, expected {group!r}")
    if settings.get("CODE_SIGN_ENTITLEMENTS") != spec.entitlements_src:
        problems.append(f"{spec.target}: CODE_SIGN_ENTITLEMENTS is {settings.get('CODE_SIGN_ENTITLEMENTS')!r}, "
                        f"expected {spec.entitlements_src!r}")
    want_skip = "NO" if spec is MAIN else "YES"
    if settings.get("SKIP_INSTALL", "NO") != want_skip:
        problems.append(f"{spec.target}: SKIP_INSTALL is {settings.get('SKIP_INSTALL')!r}, expected {want_skip} "
                        "(an embedded target that installs itself turns the archive into a generic archive)")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("check-settings")
    p.add_argument("--project", default="Strand.xcodeproj")
    p.add_argument("--prefix", required=True)
    p.set_defaults(func=cmd_check_settings)

    p = sub.add_parser("embed")
    p.add_argument("--archive", required=True)
    p.add_argument("--repo", default=".")
    p.add_argument("--prefix", required=True)
    p.set_defaults(func=cmd_embed)

    p = sub.add_parser("verify")
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--archive")
    src.add_argument("--ipa")
    p.add_argument("--prefix", required=True)
    p.add_argument("--mode", choices=("adhoc", "distribution"), required=True)
    p.add_argument("--team", default=os.environ.get("APPLE_TEAM_ID", ""))
    p.add_argument("--build-number")
    p.set_defaults(func=cmd_verify)

    args = parser.parse_args(argv)
    try:
        args.func(args)
    except CheckFailed as exc:
        gh_error(redact(str(exc), getattr(args, "team", None) or None))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
